### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by LorenzoOpWerk** [casbin/casbin.js#1]
Hi, is there a timeline for this ?

**Comment by hsluoyz** [comment]
Hi @LorenzoOpWerk , we have updated the latest progress in the README: https://github.com/casbin/casbin.js

**Comment by nodece** [comment]
@LorenzoOpWerk Hi, Try https://github.com/casbin/node-casbin.

**Comment by hsluoyz** [comment]
@LorenzoOpWerk we have finished the 1st version of Casbin.js, see: https://casbin.org/docs/en/frontend
