### ISSUE TITLE
Link to react app is broken

### ISSUE THREAD

**Issue by blestab** [casbin/casbin.js#10]
The link to the example react app appears to be broken.

![image](https://user-images.githubusercontent.com/5468546/91294872-7741c400-e79a-11ea-99ea-0a623ed56142.png)

**Comment by hsluoyz** [comment]
@kingiw

**Comment by kingiw** [comment]
Sorry for the broken link. The example is moved to https://github.com/casbin-js/examples.

**Comment by hsluoyz** [comment]
@kingiw please make a PR or commit to fix it.

**Comment by kingiw** [comment]
> @kingiw please make a PR or commit to fix it.
https://github.com/casbin/casbin-website/pull/124

**Comment by blestab** [comment]
> Sorry for the broken link. The example is moved to https://github.com/casbin-js/examples.

That's alright, thanks for the quick response.

**Comment by hsluoyz** [comment]
@kingiw and this repo's README also needs a fix: https://github.com/casbin/casbin.js#example

![image](https://user-images.githubusercontent.com/3787410/91369986-be35c500-e83f-11ea-946a-c84ad55b5341.png)

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin.js/pull/11
