### ISSUE TITLE
Fix NPM dependency registry error in CI

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin.js#126]
All our recent CIs failed like: https://github.com/casbin/casbin.js/pull/122/checks?check_run_id=3120761219

![image](https://user-images.githubusercontent.com/3787410/126449232-f1d96ba0-89c6-4d51-86f2-61e7d62ccd63.png)

We need to changed to use YARN official registry: https://registry.yarnpkg.com

**Comment by hsluoyz** [comment]
@Zxilly @Gabriel-403

**Comment by Zxilly** [comment]
@hsluoyz A totally refactor has been in progress. Maybe there's no need to maintain these.

**Comment by Gabriel-403** [comment]
working on this

**Comment by Gabriel-403** [comment]
working on this

**Comment by hsluoyz** [comment]
@Zxilly no, it's needed. Because there are still users.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin.js/commit/9e7adfe77a1d61de98057ef387ad4052325629fd
