### ISSUE TITLE
Please fix this error 

### ISSUE THREAD

**Issue by ravikumarjs-foyernet** [casbin/casbin.js#14]
I currently working on react typescript application and using casbin.js package, but when I started to react server I getting the following error. Please Help Me

Module parse failed: Unexpected token (158:32)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   async buildIncrementalRoleLinks(rm, op, sec, ptype, rules) {
|     if (sec === 'g') {
>       await this.model.get(sec)?.get(ptype)?.buildIncrementalRoleLinks(rm, op, rules);
|     }
|   } // buildRoleLinks initializes the roles in RBAC.

**Comment by hsluoyz** [comment]
It is a Node-Casbin issue: https://github.com/casbin/node-casbin/issues/197  not here.
