### ISSUE TITLE
Dependency issues in Angualr

### ISSUE THREAD

**Issue by fahussain** [casbin/casbin.js#177]
I tried using casbin.js in my Angular project but it seems casbin is dependent on some core node.js modules, path stream and fs to be more specific. Angular 12 uses webpack 5 which does not allow core node.js modules to be included in a web app. I tried some workarounds but finally gave up since I found out that casbin.js does not support RBAC with domains as mentioned here https://github.com/casbin/casbin.js/issues/31.

**Comment by giovanni-bertoncelli** [comment]
I have the same issue here. The `next` release is not platform indipendent.

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
Can't `casbin.js@next` solve this?

**Comment by danverde** [comment]
Experiencing the same thing. Here's a repo: https://github.com/danverde/CasbinJS-React
I did make sure to install `casbinjs@next`. Looks like it ended up installing 1.0.0, rather than 1.0.1 that I got by installing `casbin.js`

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
Thanks @danverde, I know how to resolve it.

**Comment by nodece** [comment]
Because we are incorrect design, this version is confusing, we are decided to improve the `node-casbin` repo, the next version casbin has been released, the `casbin@next` can be available on NPM. 

but this version number is incorrect, should be `6.0.0-beta.x`, not `5.14.0-beta.x`. This version is working on React, and Ng.

**Comment by danverde** [comment]
@nodece  So I need to use version `6.0.0-beta.x` of the `node-casbin` repo rather than the `casbin.js` repo? or is/will there be a release of `casbin.js` build off the correct version of `node-casbin`?

**Comment by nodece** [comment]
> So I need to use version 6.0.0-beta.x of the node-casbin repo rather than the casbin.js repo?

Yes, you can install this by `yarn add casbin@next`, then select the `5.14.0-beta.3`.

> or is/will there be a release of casbin.js build off the correct version of node-casbin?

We don't continue to release the casbin.js to instead of node-casbin.

**Comment by danverde** [comment]
Installing `casbin@next` doesn't work:
![image](https://user-images.githubusercontent.com/19293059/159302309-1bbc9270-8d72-47fb-8563-d6e2cf56e05e.png)

And `node-casbin 5.14.0-beta.3` doesn't work in the browser either. It throws the same error I got when trying to run `casbin.js`

**Comment by danverde** [comment]
I was able to get `casbin.js` running by ejecting the react project and then updating the webpack config file to disable source maps for `node_modules` and disabling the polyfill for `path`.

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
Sorry, `casbin@beta` is correct.

**Comment by nodece** [comment]
> Installing `casbin@next` doesn't work: ![image](https://user-images.githubusercontent.com/19293059/159302309-1bbc9270-8d72-47fb-8563-d6e2cf56e05e.png)
> 
> And `node-casbin 5.14.0-beta.3` doesn't work in the browser either

Could you provide the log that doesn't work in the browser?
