### ISSUE TITLE
A simple and easy to use casbin.js library for Vue based 

### ISSUE THREAD

**Issue by Gabriel-403** [casbin/casbin.js#181]
Recently, I will package a Vue plug-in library that simply uses casbin. The design and use will refer to the implementation method of Vue router. We need a more concise, convenient and user-friendly parameter transmission method. I hope to listen to your opinions. These are some simple designs, which will be supplemented later

`import Vue from 'vue'
import { VueCasbin } from 'vue-casbin-v2.x'

Vue.use(VueCasbin, { })

new Vue({
  methods: {
    async vcasbin () {
      //todo
    }
  },
  template: '<button @click="vcasbin">Execute use vue-casbin-v2.x</button>'
})`

**Comment by Zxilly** [comment]
You can rewrite https://github.com/casbin-js/vue-authz.

**Comment by Gabriel-403** [comment]
@Zxilly 
I know this, and I understand what you mean, but at present, its design idea is different from mine. However, it can indeed be used as a template, but I will roughly make many new things and functions. I also want to know the needs of users. We need to brainstorm.I'd like to hear from you，thanks！！！❤

**Comment by Gabriel-403** [comment]
@Zxilly I will develop on the vue-caspin-v2. X branch and support vue3 in the future，Refactoring adapts to the current new Casbin.js

**Comment by Gabriel-403** [comment]
@Zxilly I will develop on the vue-caspin-v2. X branch and support vue3 in the future，Refactoring adapts to the current new Casbin.js

**Comment by hsluoyz** [comment]
Closed as stale.
