### ISSUE TITLE
Implements CasbinJsGetPermissionForUser for .Net

### ISSUE THREAD

**Issue by elmankross** [casbin/casbin.js#19]
Hello. According to my comment from [docs ](https://casbin.org/docs/en/frontend#comment-5146439045) it really will be helpful to implements _CasbinJsGetPermissionForUser_ for .NET because of needs to use dynamic auth on the frontend.
Idk it should be a derived library or a part of the existing one, but I think the first variant is better. 

Is there contributors can do this?
@hsluoyz

**Comment by hsluoyz** [comment]
@elmankross are you willing to make a PR? If yes, we welcome your contribution.

If no, please send this issue to the Casbin.NET repo: https://github.com/casbin/Casbin.NET , so our .NET guys will take the ticket there :)

**Comment by elmankross** [comment]
Ok, I got it. Just will go to .NET guys to figure out what we can do with it :D

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casbin/Casbin.NET/issues/105
