### ISSUE TITLE
Documentation on different modes using Authorizer.can()

### ISSUE THREAD

**Issue by abel30567** [casbin/casbin.js#203]
When I use Authorizer.can() in `manual` mode it returns a `Boolean` while when using Authorizer.can() in `auto` mode it returns an `Array` containing whether or not the user has access. 

Also would be great to have a sample response from the API that is needed to use this in `auto` mode.

**Comment by Zxilly** [comment]
old casbin.js is no longer under matainered. You can find an active version at branch v1
