### ISSUE TITLE
Examples are incorrect/misguiding

### ISSUE THREAD

**Issue by fgblomqvist** [casbin/casbin.js#24]
The node-casbin enforcer's `enforce` is async, yet you call it as if it was sync in both the readme of this project and the [example project linked](https://github.com/casbin-js/examples/blob/master/react/src/CasbinDemo.js).

It is not trivial to use an async enforcer together with React rendering, probably makes sense to not make it look simpler than it is.

**Comment by hsluoyz** [comment]
@fgblomqvist sorry, moved back

**Comment by hsluoyz** [comment]
@fgblomqvist `enforceSync()` is added to Node-Casbin: https://github.com/casbin/node-casbin/pull/230 , closed here.
