### ISSUE TITLE
Make a React authz middleware for Casbin.js

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin.js#26]
See:

- https://github.com/casbin/casbin.js/issues/2
- https://github.com/casbin/casbin.js/issues/12

Finally, this middleware will be tested and used on our own forum: https://github.com/casbin/casbin-forum

**Comment by Ishaan28malik** [comment]
@hsluoyz I would like to work on this but I haven't worked on building a middleware previously using **JS** or any language, can you give me a hint or guide me ? maybe I can work and complete this then.

**Comment by Zxilly** [comment]
ref to: https://github.com/casbin-js/react-authz/pull/1
