### ISSUE TITLE
casbin.js v0.4.1 not working with react-scripts 5

### ISSUE THREAD

**Issue by GhostyJade** [casbin/casbin.js#268]
Hi.
Long story short, I need to update my project's react-scripts from v4 to v5.
The issue is that the casbin.js package throws an atrocious list of errors saying that lots of modules that webpack exported in v4 no longer are exported in v5 and breaks everything.

In particular, fs, buffer, stream (from csv-parser dependency in your casbin package), path (from casbin's picomatch package dependency).

There are any plans to support react-scripts 5 or should I consider to try ways to fix this issue myself?

Thanks in advance.

**Comment by hsluoyz** [comment]
@nodece @kingiw

**Comment by hsluoyz** [comment]
@keyuzhen

**Comment by ferifahrul7** [comment]
any news?

**Comment by GhostyJade** [comment]
@ferifahrul7 no, not from casbin manteiners.
My team has decided not to use casbin.js anymore and use casl instead. We are also working to implement our custom permission management for our backend infrastructure.

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 plz work on this

/cc @nodece @Zxilly

**Comment by JohnnyTheTank** [comment]
hi guys. any progress on this topic?
