### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by sukhtulgaotgonbayar** [casbin/casbin.js#270]
![image](https://user-images.githubusercontent.com/115963105/197670424-a92fbf47-adeb-4837-b693-09f5c4fa1fce.png)

I'm using it on Next.js as port of a backend Casbin service. But its gives me this error. 
Maybe it is from the Webpack settings?

**Comment by pnvasko** [comment]
Try look here https://github.com/casbin/node-casbin/issues/386

**Comment by GhostyJade** [comment]
Are you using react-scripts 5?
