### ISSUE TITLE
Error in casbin.js advanced usage.

### ISSUE THREAD

**Issue by cwgitadmin** [casbin/casbin.js#273]
![Screenshot from 2023-06-06 08-30-29](https://github.com/casbin/casbin.js/assets/80871713/cdaadea1-ff14-4395-a5b0-5f28bf186cc3)

**Comment by cwgitadmin** [comment]
API Code
```exports.getUserPermissions = async function (req, res) {
  try {
    const subject = req.query.subject;
    var e = await enforcer();
    var permissions = await casbin.casbinJsGetPermissionForUser(e, subject);
    res.json(permissions);
  } catch (error) {
    console.log("getPermissionsByRoleId:", error);
    res.status(400).json(error.message);
  }
};```

**Comment by cwgitadmin** [comment]
Frontend Code

```
 const authorizer = new Authorizer(
    "auto", // mode
    {
      endpoint: `http://localhost:3001/roles/user-permissions`,
      requestHeaders: {
        method: ["GET"],
        ContentType: ["application/json"],
        Authorization: [`Bearer ${current?.token}`]
      }
    }
  );

  // Set your visitor.
  // Casbin.js will automatically sync the permission with your backend Casbin service.
  authorizer.setUser("74");

  // Evaluate the permission
  const result = await authorizer.can("read", "/dashboard/*");
  console.log("result", result);
  
  ```

**Comment by cwgitadmin** [comment]
Please help me to fix this error.

**Comment by hsluoyz** [comment]
@cwgitadmin hi, why close?

**Comment by vasanth123** [comment]
> I got solution for above mentioned issue

pls provide the solution here

**Comment by vasanth123** [comment]
I am facing same issue

**Comment by Dias1c** [comment]
Why closed? @vasanth123 did you fix this issue? Please share your solution here :)

**Comment by Dias1c** [comment]
I have solved this problem. The problem was in order of request.

When you calling method `can` of `authorizer` class, it alwas enforces your request in own order:
```
enforcer.enforce(this.user, domain, object, action)
```
And if you have own request order, `authorizer.can` will throws error.

So I created own library that solves this problem, you can write your request in order which you want.
https://github.com/Dias1c/casbin-js/tree/main

**Comment by hsluoyz** [comment]
@Dias1c can you make PR to merge this to this repo?
