### ISSUE TITLE
 Error in casbin.js advanced usage - Uncaught (in promise) Error: Enforcer not initialized

### ISSUE THREAD

**Issue by vasanth123** [casbin/casbin.js#276]
> I got solution for above mentioned issue

pls provide the solution here

_Originally posted by @vasanth123 in https://github.com/casbin/casbin.js/issues/273#issuecomment-1736543097_

**Comment by vasanth123** [comment]
### **API Code**
`app.get('/api/casbin', async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  try {
    const subject = req.query.subject;
    var e =await newEnforcer('model.conf', 'rbac_policy.csv');
    //var e =new Enforcer();
    //e.initWithFile('model.conf', 'rbac_policy.csv');
    var permissions = await casbinJsGetPermissionForUser(e, subject);
    
   // res.setHeader('Access-Control-Allow-Origin', '*');
    res.send({data:permissions});
  } catch (error) {
    console.log("getPermissionsByRoleId:", error);
    res.status(400).json(error.message);
  }
});`


**### Frontend**

 `const authorizer = new Authorizer(
    "auto", // mode
    {
      endpoint: `http://localhost:3001/api/casbin`,
      requestHeaders: {
        method: ["GET"],
      }
    }
  );

  // Set your visitor.
  // Casbin.js will automatically sync the permission with your backend Casbin service.
  authorizer.setUser("74");

  // Evaluate the permission
  const result = await authorizer.can("read", "/dashboard/*");
  console.log("result", result);`

**Comment by vasanth123** [comment]
casbinJsGetPermissionForUser return all user policy instead of current user

**Comment by hsluoyz** [comment]
@vasanth123 what's your question?

**Comment by vasanth123** [comment]
@hsluoyz While creating this issue. I have face Enforcer not initialized issue in frontend react app.

Issue is fixed after place my Api call in  componentWillMount() but backend service i.e  casbinJsGetPermissionForUser is return all user policy info instead of given user info. 

I have paste my policy.csv for your reference

p, *, /, GET
p, admin, /*, GET
p, admin, /rest, GET
p, admin, /test, POST
p, vasanth, /test12, GET
p, vasanth, /test12, POST

in frontend,
authorizer.setUser('vasanth'); Api call is trigger once setup the user info but backend service return whole policy including admin data instead of vasanth info.

**Comment by vasanth123** [comment]
@hsluoyz 
In above link, "Why casbin.js" section mention as "_We also avoid storing all the policies at the frontend. The user can only access their own permission, but has no knowledge about the access-control model and other users' permissions._".
![casbin](https://github.com/casbin/casbin.js/assets/10614880/fcdba662-1110-4d00-b76b-28b2fcb394e8)

But currently, Its storing all the policies in the local storage in frontend. Please correct me if i am missing anything

**Comment by vasanth123** [comment]
@hsluoyz Any update on this? Please let me know if my understanding is correct.

**Comment by Dias1c** [comment]
> @hsluoyz In above link, "Why casbin.js" section mention as "_We also avoid storing all the policies at the frontend. The user can only access their own permission, but has no knowledge about the access-control model and other users' permissions._". I have attached screenshot below for reference
> 
> ![casbin](https://private-user-images.githubusercontent.com/10614880/271049223-fcdba662-1110-4d00-b76b-28b2fcb394e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMzk3OTAsIm5iZiI6MTcyMTIzOTQ5MCwicGF0aCI6Ii8xMDYxNDg4MC8yNzEwNDkyMjMtZmNkYmE2NjItMTExMC00ZDAwLWI3NmItMjhiMmZjYjM5NGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDE4MDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYjQ1ZjI5Y2Y5ZDM1YmY1NzczMDRkZmVlODkxZThjNGJlMGI3OTA3NDdmNWEyNDI2Yzk0ZDhlNzcxNWM1YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dudz24ls0CznsE3JiGNUJNpgHon9yFg7doJGAdB2kdA)
> 
> But currently, Its storing all the policies in the local storage in frontend. Please correct me if i am missing something

I also had this problem, and as you wrote the problem was in order of request.

When you calling method can of authorizer class, it alwas enforces your request in own order:
```
enforcer.enforce(this.user, domain, object, action)
```

And if you have own request order, authorizer.can will throws error.

So I created own library that solves this problem, you can write your request in order which you want.
https://github.com/Dias1c/casbin-js/tree/main

**Comment by hsluoyz** [comment]
@vasanth123 can you make a PR?
