### ISSUE TITLE
Casbin.js 0.1.0 with react-scripts 4.0.2 conflict

### ISSUE THREAD

**Issue by kavindapelpola** [casbin/casbin.js#28]
Hi, when I add Casbin.js to my react project I get the error below. To use Casbin.js I need to downgrade Casbin.js to a version that is not tied to babel-loader 8.2.2, but this cannot be the long term solution. Can you advise how to proceed?

The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.1.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  /Users/kavindapelpola/src/atos-ams/packages/ams/ui/node_modules/babel-loader (version: 8.2.2)

**Comment by hsluoyz** [comment]
@17bit

**Comment by 17bit** [comment]
fixed https://github.com/casbin/casbin.js/pull/30

**Comment by 17bit** [comment]
> Hi, when I add Casbin.js to my react project I get the error below. To use Casbin.js I need to downgrade Casbin.js to a version that is not tied to babel-loader 8.2.2, but this cannot be the long term solution. Can you advise how to proceed?
> 
> The react-scripts package provided by Create React App requires a dependency:
> 
> "babel-loader": "8.1.0"
> 
> Don't try to install it manually: your package manager does it automatically.
> However, a different version of babel-loader was detected higher up in the tree:
> 
> /Users/kavindapelpola/src/atos-ams/packages/ams/ui/node_modules/babel-loader (version: 8.2.2)

Hi.  ` Try to use yarn add babel-loader@8.1.0`

**Comment by hsluoyz** [comment]
@Zxilly can you help fix this?

**Comment by hsluoyz** [comment]
@Zxilly plz make a new release.

**Comment by Zxilly** [comment]
@hsluoyz released
https://www.npmjs.com/package/casbin.js/v/0.1.2

**Comment by hsluoyz** [comment]
@Zxilly and GitHub releases, actually I found this repo doesn't have even the previous GitHub releases. @Zxilly can you add them too?

**Comment by Zxilly** [comment]
@hsluoyz I can add v0.1.2 and v0.0.1, but i didn't know which commit the previous releases should pinned to.

**Comment by Zxilly** [comment]
@hsluoyz I added all i can find, but I really didn't which commit ref to `v0.0.1`

**Comment by hsluoyz** [comment]
@Zxilly I have added them: https://github.com/casbin/casbin.js/releases
