### ISSUE TITLE
CasbinJsGetPermissionForUser 搭配casbin.js 工作存在问题

### ISSUE THREAD

**Issue by ALiangTech** [casbin/casbin.js#281]
### 版本
go-casbin 	github.com/casbin/casbin/v2 v2.85.0 indirect
casbin.js     "casbin.js": "^0.5.1"

### 通过endpoint 远程获取权限
 ```
 const authorizer = new Authorizer(
    'auto', // mode
    {
      endpoint: `${import.meta.env.VITE_HTTP_URL}/v1/permission`,
      requestHeaders: {
        Authorization: [Authorization],
      },
    },
  );
```

接口返回：

`
{
    "data": "{\"g\":[[\"g\",\"test\",\"account\"],[\"g\",\"test\",\"account_add\"]],\"m\":\"[request_definition]\\nr = sub, obj, act\\n[policy_definition]\\np = sub, obj, act\\n[role_definition]\\ng = _, _\\n[policy_effect]\\ne = some(where (p.eft == allow))\\n[matchers]\\nm = r.sub == p.sub \u0026\u0026 keyMatch(r.obj, p.obj) \u0026\u0026 regexMatch(r.act, p.act) || r.sub == \\\"root\\\"\\n\",\"p\":[[\"p\",\"account\",\"/account/*\",\"(get|post)\"],[\"p\",\"account_add\",\"/account_add\",\"post\"],[\"p\",\"account_del\",\"/account_del\",\"post\"],[\"p\",\"permission\",\"/permission\",\"get\"]]}\n",
    "error": null
}
`

使用：
```
  authorizer.can("post", "/account_add").then(result => {
    can.value = result;
  });
```

期望：
result 的值是true 实际是false

**Comment by hsluoyz** [comment]
@ALiangTech plz use English in all texts. This issue will be deleted shortly.
