### ISSUE TITLE
CasbinJsGetPermissionForUser API for JAVA

### ISSUE THREAD

**Issue by rajdeepkhandelwal** [casbin/casbin.js#282]

**Comment by hsluoyz** [comment]
@rajdeepkhandelwal this repo is frontend Javascript, not Java

**Comment by hsluoyz** [comment]
@rajdeepkhandelwal jCasbin (Casbin Java version) has the API: `CasbinJsGetPermissionForUser`: https://github.com/search?q=repo%3Acasbin%2Fjcasbin%20CasbinJsGetPermissionForUser%20&type=code
