### ISSUE TITLE
CasbinJsGetPermissionForUser is too limited

### ISSUE THREAD

**Issue by dschmidt** [casbin/casbin.js#31]
Hey everyone,

I'm checking out casbin because I'm considering to use it for a project. What especially caught my interest, is the new casbin.js because no other go authorization framework seems to provide anything similar. While I was playing around with it, I noticed limitations of `CasbinJsGetPermissionForUser`, which I would like to discuss:

(I hope this is the right repository to discuss, otherwise feel free to move the issue around)

### deny permissions 

`CasbinJsGetPermissionForUser(...)` cannot be used with any allow/deny models because the `.eft` information is completely stripped, i.e. any `deny` permission becomes an `allow` permission.

Standard  [rbac_with_deny_model.conf](https://github.com/casbin/casbin/blob/master/examples/rbac_with_not_deny_model.conf) and [rbac_with_deny_policy.csv](https://github.com/casbin/casbin/blob/master/examples/rbac_with_deny_policy.csv) make  `CasbinJsGetPermissionForUser(e, "alice")` return 
```
{"read":["data1","data2"],"write":["data2","data2"]}
```

Not only is `data2` duplicated, but the second time it's actually a `deny` rule and here it shows up as a `allow` rule.

#### Idea

This might be solvable by more or less directly serializing the permissions as they are returned from `e.GetImplicitPermissionsForUser(user)`. Otherwise I'm afraid with whatever we come up, will miss information for other model configurations because of the generic nature of casbin.

This would probably mean that casbin.js would need to have access to the model definition to know how to interpret the permissions?
If that wasn't the case, we wouldn't need the model configuration on the server side either ...

### role inheritance

`CasbinJsGetPermissionForUser(...)` does not handle permissions for subroles.

Standard  [rbac_with_resource_roles_model.conf](https://github.com/casbin/casbin/blob/master/examples/rbac_with_resource_roles_model.conf) and [rbac_with_resource_roles_policy.csv](https://github.com/casbin/casbin/blob/master/examples/rbac_with_resource_roles_policy.csv) make  `CasbinJsGetPermissionForUser(e, "alice")` return 
```
{"read":["data1"],"write":["data_group"]}
```

So `e.Enforce("alice", "data2", "write")` will be true on the backend, but false on the frontend because  because subroles are missing from the response and so unknown to the frontend.

#### Idea

For this very specific use case I added this to the loop:
```
                subRoles, err := e.GetUsersForRole(role)
		if err != nil {
			continue
		}
		for j := 0; j < len(subRoles); j++ {
			permission[action] = append(permission[action], subRoles[j])
		}

```

and it works. But it only handles one level of subroles (does casbin on the server side handle nested resource role permission deeper than one level?) and it seems to be very specific to this use case.

To make this a bit more abstract:
all roles of the user and the roles of resources that the user has permissions for should be known to the frontend.

Can this be done in a generic way at all and especially without leaking possibly sensitive information to the frontend?

### Conclusion

`CasbinJsGetPermissionForUser` (and the format it returns) is in my humble opinion *too* limited. The structure of the response should be adjusted to be more generic and casbin.js should be adjusted to reflect a new structure.
If possible the data returned should be extended with resource roles.

I think it's rather easy to come up with a solution that works for a specific use case, but doing it in a generic way that's "upstreamable" might be rather hard. I'd be happy to hear your thoughts what can be done with reasonable effort as someone who is new to the project and then I'd be happy to work on that and upstream it.

Best regards,
Dominik

P.S.: I'm also in your Gitter channel and happy to answer questions or discuss there too

**Comment by Zxilly** [comment]
> No worries. It sounds like sending the full model + a filtered policy would do it. I.e. what @dschmidt said, just serialize the output of `GetImplicitPermissionsForUser` and send that, along with the full actual model (that shouldn't be sensitive info).
> Am I missing something?

The frontend should be always considered as unsafe, maybe send the whole model not a good idea. This  provides additional information and may cause potential security vulnerability.

**Comment by hsluoyz** [comment]
@dschmidt Casbin.js now bases on casbin-core and contains all Casbin functionalities (keymatch, RBAC, ABAC) now: https://github.com/casbin/casbin.js/pull/271
