### ISSUE TITLE
The installation commands in the docs do not work properly

### ISSUE THREAD

**Issue by Kininaru** [casbin/casbin.js#34]
In [this](https://casbin.org/docs/en/frontend) doc we told users to install Casbin.js via 
```
npm install casbin.js
```
But node reported an error: 
```
Error: Cannot find module 'casbin'
```
I used the command
```
npm install casbin
```
then the code worked properly.
So I wonder if this is a bug, or just a mistake in our docs.

**Comment by Kininaru** [comment]
```
npm install casbin.js
```
and 
```
npm install casbin
```
These 2 commands are both indispensable.

**Comment by Zxilly** [comment]
working on this
