### ISSUE TITLE
dependency with axios should be updated

### ISSUE THREAD

**Issue by remware** [casbin/casbin.js#37]
Using yarn install in react example (cabinjs ^0.1.0)
I get this warning when installing for first time
casbin.js > axios@0.19.2: Critical security vulnerability fixed in v0.21.1.
any plans for updating the dependency?

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
working on this

**Comment by Zxilly** [comment]
https://github.com/casbin/casbin.js/blob/7b8763a74a3f0c64d8be0b6c53c8592d7c4674d5/package.json#L41-L48
axios is `^0.21.1`, and seems this is not a problem
@remware Could you please help to reproduce?

In fact, casbin.js change the api in the `v0.1.0`, but example did not update.
I recommend you read the source directly

**Comment by hsluoyz** [comment]
@kingiw can you add the casbin organization: https://www.npmjs.com/org/casbin to the owners of the package: https://www.npmjs.com/package/casbin.js ? Current it seems to be under your personal account.

**Comment by remware** [comment]
I was reading the example from here: https://casbin.org/docs/en/frontend
then I modified a bit for my react app using scripts 4.0.3,
`import { Authorizer } from 'casbin.js'
....
 this.auth = new Authorizer(
            'auto' ,
            { endpoint: config.GoEndpoint }
        );
...
  this.auth.setUser("Tom");
....
  result = this.auth.can("read", "data1");
....
`

but somehow the npm package is broken as the error I get is
/node_modules/casbin.js/lib/Authorizer.js
Module not found: Can't resolve 'casbin' in ...casbin.js/lib

let me know for more info

**Comment by Zxilly** [comment]
@remware Yes, this is also a fixed bug by https://github.com/casbin/casbin.js/commit/0aeba6e5c9b3b9e89709c94d155129661a69bf77 but not published.
We will release the correct version ASAP.

**Comment by Zxilly** [comment]
@remware A new version v0.1.1 with fixes have been released at https://www.npmjs.com/package/casbin.js/v/0.1.1
Please let me know if you have any other question.

**Comment by remware** [comment]
> @remware A new version v0.1.1 with fixes have been released at https://www.npmjs.com/package/casbin.js/v/0.1.1
> Please let me know if you have any other question.

Thanks, all is up and running. Appreciated it.
