### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by ThomasLohmann** [casbin/casbin.js#41]
Hi everyone,

it would be great if you can also support Angular. 

Best regards,
Thomas

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by hsluoyz** [comment]
@ThomasLohmann created: https://github.com/casbin-js/angular-authz

**Comment by Zxilly** [comment]
I never used Angular, I can't do this.

**Comment by ThomasLohmann** [comment]
@hsluoyz I'm quite busy with our own project at the moment. So unfortunately I'm not able to contribute currently.

**Comment by ajayaallen** [comment]
I want to contribute, How can I

**Comment by Zxilly** [comment]
@ajayaallen If you complete an early version, you can send a PR to https://github.com/casbin-js/angular-authz

**Comment by hsluoyz** [comment]
Moved to: https://github.com/casbin-js/angular-authz/issues/1
