### ISSUE TITLE
We need unit testing for this repo

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin.js#43]
Our latest v0.1.2 has been reported to have bugs when importing:

![image](https://user-images.githubusercontent.com/3787410/111092590-6f4c4480-8571-11eb-9862-84d03b4e02c0.png)

We should stop such things happening again.

**Comment by Zxilly** [comment]
Now we have unittests for code itself. But didn't have tests for release.
I will add a CI later.

**Comment by Zxilly** [comment]
We already have unit tests under https://github.com/casbin/casbin.js/tree/master/src/__test__.

**Comment by hsluoyz** [comment]
@Zxilly 

First, your link is 404:

![image](https://user-images.githubusercontent.com/3787410/111338063-96aa2b00-86b1-11eb-8ccc-ff8e29632f9c.png)

Second, plz mention the PR or commit (which shouldn't happen because people are not supposed to directly commit to master) that add the unit tests, instead of the unit test file itself.

**Comment by Zxilly** [comment]
@hsluoyz There is a useless `.` after the link, I have removed it.
Unit test was added in a much earlier version https://github.com/casbin/casbin.js/commit/3ec7aead69a7e9ec0b24d00b8835ad8a05406dbc

**Comment by hsluoyz** [comment]
OK, [link](https://github.com/casbin/casbin.js/tree/master/src/__test__)
