### ISSUE TITLE
Embed Node-Casbin directly into Casbin.js

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin.js#52]
Currently, Casbin.js is a self-made authorization mechanism called Authorizer, which is much different with Casbin's enforcer.

Now we decided to remove all those stuff and let Casbin.js just be a wrapper of [Node-Casbin](https://github.com/casbin/node-casbin). Node-Casbin can run both on browser and Node.js. For browser use, it has been used in Casbin online editor: https://github.com/casbin/casbin-editor

But Node-Casbin may need to be adjusted like adding Sync functions, to facilitate the use of frontend.

**Comment by Zxilly** [comment]
After gzip, node-casbin still need more than 400kb space, which is too large for the frontend.
If we did want to implement this, we should make a separate light-weight branch on node-casbin.
