### ISSUE TITLE
Support for roles in auto mode

### ISSUE THREAD

**Issue by GhostyJade** [casbin/casbin.js#54]
I'm trying to integrate casbin.js for a ReactJS app that needs to have roles but it seems that this library can't support roles. (I've tested with permissions and it works)

I've tried using golang (using CasbinJsGetPermissionForUser to retrieve data) and C# (with CasbinJsGetPermissionForUser defined as a custom function) as backend to test if was my implementation issue or not.

I've used the default RBAC model.conf file and both MSSQL database and default csv file for policies

I'm using the latest version of both casbin.js and node-casbin as dependencies.

Now I ask, is this a missing feature or a bug?
Thanks in advance.

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
You can directly use node-casbin.

**Comment by GhostyJade** [comment]
Where? How?

I mean
I'm making a frontend and using your Authorizer class to manage permissions. If I have to use node-casbin it means that I have to do the "can/cannot" methods by myself, right?

Or is a backend issue? (Even if I've tested with your golang library and it doesn't work)
Or should I have to use Node as my backend?

**Comment by GhostyJade** [comment]
Where? How?

I mean
I'm making a frontend and using your Authorizer class to manage permissions. If I have to use node-casbin it means that I have to do the "can/cannot" methods by myself, right?

Or is a backend issue? (Even if I've tested with your golang library and it doesn't work)
Or should I have to use Node as my backend?

**Comment by Zxilly** [comment]
@GhostyJade Node-Casbin is also available for frontend project.
As for now, casbin.js is just a wrapper for node-casbin. You can use enforce() API instead.
It's possible to implement what you asked for. But you may need to wait for some time.

**Comment by GhostyJade** [comment]
Thanks for the additional information, I'm gonna try it now.

**Comment by GhostyJade** [comment]
I've decided for now to integrate casbin using the manual approach, since it works without any issues.
I think that I can close this issue.
