### ISSUE TITLE
Enforcer not initialized

### ISSUE THREAD

**Issue by arigon** [casbin/casbin.js#56]
Hello

I am trying to get casbin.js working in ReactJS. I added the code as described in the example:

```js
const authorizer = new Authorizer('auto', {
      endpoint: '/api/casbin'
});
authorizer.setUser(userID);
    authorizer.can('admin', 'account_123').then(() => {
      console.log('it works');
    });
```

The response from the API:
![image](https://user-images.githubusercontent.com/11992526/115896207-77927c00-a45b-11eb-86e7-6db986b036e7.png)

The result is an error: _Unhandled Rejection (Error): Enforcer not initialized_

What am I missing?

Thanks
Alex

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
working on this

**Comment by Zxilly** [comment]
@arigon please notice, `setUser()` return a Promise, please use `.then()` callback or `await`.
