### ISSUE TITLE
Server response is already parsed json -> parsing it again fails

### ISSUE THREAD

**Issue by arigon** [casbin/casbin.js#58]
Hello

in https://github.com/casbin/casbin.js/blob/ca5343cffa4b059c7a7d9b07afe72064658b9000/src/Authorizer.ts#L88 json.parse is called on an already parsed object. Axios is already parsing a result json into an object because it's a feature: "Automatic transforms for JSON data"

Therefore, the use of this library fails with: _Unexpected token o in JSON at position 1_

Solution:
Either set the Axios _responseType_ to text or remove the json.Parse() completely.

Alex

**Comment by hsluoyz** [comment]
@arigon can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by arigon** [comment]
It's not working. The result is undefined.

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
@arigon Sorry, I got the reason wrong.
In fact, the default auto mode assume the endpoint server respond something like:
```json
{
                "other":"other",
                "data": "What you get from `CasbinJsGetPermissionForUser`"
            }
```
This is a undocument behavior. I will add this later.

**Comment by hsluoyz** [comment]
@Zxilly plz add to docs now: https://github.com/casbin/casbin-website

**Comment by hsluoyz** [comment]
@arigon can you make a PR to fix this issue?

**Comment by arigon** [comment]
> @arigon can you make a PR to fix this issue?

I'm not familiar with TypeScript, sorry.

**Comment by hsluoyz** [comment]
@Zxilly
