### ISSUE TITLE
TypeError: can't access property "toString", args[2] is undefined

### ISSUE THREAD

**Issue by bohdan-snext** [casbin/casbin.js#62]
Hello
I am trying to get casbin.js (0.3.2) working in ReactJS. I added the code as described in the example:

```js
const getAuthorizer = async () => {
        const auth = new Authorizer(
            'auto', // mode
            { endpoint: url.href });
        await auth.setUser(enforce.user);
        const perms = await auth.can(enforce.action, enforce.resource)
        setPermissions(perms)
        return auth

    }
```

The response from the API:
![Screen Shot 2021-05-05 at 1 02 36 PM](https://user-images.githubusercontent.com/51936902/117202151-56f2ec00-ada2-11eb-91dc-e2cfd4cc4595.png)

The result is an error: Uncaught (in promise) TypeError: can't access property "toString", args[2] is undefined
![Screen Shot 2021-05-05 at 1 03 00 PM](https://user-images.githubusercontent.com/51936902/117202197-65d99e80-ada2-11eb-8ab7-ab627d27361b.png)

What am I missing?

Thanks
Bohdan

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
@bohdan-snext In fact, the default auto mode assume the endpoint server respond something like:
```json
{
    "other":"other",
    "data": "What you get from `CasbinJsGetPermissionForUser`"
}
```
in json format.

**Comment by bohdan-snext** [comment]
@Zxilly 
There's the code for the endpoint server response:
```
async getUserPermission(params: { subject: string }, ctx: IRequestContext): Promise<Record<string, string>> {
	const enforcer: Enforcer = await CasbinEnforcer();
	const permissions = await casbinJsGetPermissionForUser(enforcer, params.subject);
	return { data: permissions };
}
```

**Comment by Zxilly** [comment]
@bohdan-snext Could you please provide a minimal reproducible example? I think there's something wrong on `node-casbin`, but I failed to reproduce.

**Comment by bohdan-snext** [comment]
@Zxilly 
rbac-model.conf:
```js
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = (g(r.sub, p.sub, r.dom) && r.dom == p.dom && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)) || r.sub == "admin"
```
rbac-policy.csv:
```js
p,[admin, /*, *, allow]
g,[testUser, admin]
```

Backend (NodeJs/Express):
```js
import express from "express";
import cors from 'cors';
import { newEnforcer, casbinJsGetPermissionForUser, Enforcer } from "casbin";
const path = require("path");

let enforcer: Enforcer;
const app = express();
app.use(cors());

app.get("/permissions/", async (req, res) => {
  const params = req.query as any;
  const permissions = await casbinJsGetPermissionForUser(
    enforcer,
    params.subject
  );
  console.log(permissions);
  res.send({ data: permissions });
});

app.listen(3000, async () => {
  console.log("The application is listening on port 3000!");
  enforcer = await newEnforcer(
    path.join(process.cwd(), "src", "rbac_model.conf"),
    path.join(process.cwd(), "src", "rbac_policy.csv")
  );
});
```

Frontend:
```js
        const sub = "testUser";
        const obj = "/upload/*";
        const act = "read";
        const url = `http://localhost:3000/permissions`;
        const auth = new Authorizer(
            "auto", // mode
            { endpoint: url }
        );
        await auth.setUser(sub);
        const perms = await auth.can(act, obj);
```
Response from server (raw):
```js
{"data":"{\"m\":\"[request_definition]\\nr = sub, obj, act\\n[policy_definition]\\np = sub, obj, act\\n[role_definition]\\ng = _, _\\n[policy_effect]\\ne = some(where (p.eft == allow)) && !some(where (p.eft == deny))\\n[matchers]\\nm = (g(r.sub, p.sub, r.dom) && r.dom == p.dom && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)) || r.sub == \\\"admin\\\"\",\"p\":[[\"p\",\"[admin\",\"/*\",\"*\",\"allow]\"]]}"}
```

Error:
![Screen Shot 2021-05-06 at 9 07 53 AM](https://user-images.githubusercontent.com/51936902/117330465-937a2280-ae4a-11eb-81d4-1deb860275d7.png)

**Comment by Zxilly** [comment]
@bohdan-snext 
There seems some error in your code.
1. `p,[admin, /*, *, allow]` is not right. You should use something like `p,admin, /*, *, allow`
2. Your policy_definition is `p = sub, obj, act`, which means you should have there 3 variables, however, your have 4 in policies.
3. If you want to use RBAC with domain, you should define `role_definition` with `g = _, _, _`.
So your code results in undefined behavior, which cause unexpected error.

**Comment by bohdan-snext** [comment]
@Zxilly Thanks, let me check it.
One more quick question: `casbinJsGetPermissionForUser ` doesn't retrieve permissions for inherited roles, right?

**Comment by Zxilly** [comment]
@bohdan-snext Yes, it used to process with user. As for now, it just sent the whole model and all policies.

**Comment by hsluoyz** [comment]
Closed as resolved.
