### ISSUE TITLE
Why the dependabot in this repo doesn't follow semantic-pr in title?

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin.js#69]
This repo: https://github.com/casbin/casbin.js/pull/68

![image](https://user-images.githubusercontent.com/3787410/119756105-a1fdac00-bed5-11eb-99ad-8636666d850c.png)

Another repo: https://github.com/node-casbin/mongoose-adapter/pull/45

![image](https://user-images.githubusercontent.com/3787410/119756122-a924ba00-bed5-11eb-95b0-00b96b75609a.png)

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
@hsluoyz plz give me admin permission to this repo

**Comment by hsluoyz** [comment]
@Zxilly granted

**Comment by hsluoyz** [comment]
@Zxilly any progress?
