### ISSUE TITLE
Add tests and the badges 

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin.js#8]
Ideally we want to have all the badges that Node-Casbin has: https://github.com/casbin/node-casbin#node-casbin

![image](https://user-images.githubusercontent.com/3787410/90304509-4684a380-deeb-11ea-92a0-3fe68498f7df.png)

**Comment by hsluoyz** [comment]
@kingiw can you take this issue?

**Comment by hsluoyz** [comment]
@kingiw any update?

**Comment by kingiw** [comment]
> @kingiw any update?

I will do it these days.

**Comment by kingiw** [comment]
https://github.com/casbin/casbin.js/pull/13 fix this. Close.
